#!/bin/bash

SESSION="sudoku-solver"
STARTDIR="$(pwd)"

echo $STARTDIR


tmux has-session -t $SESSION 2>/dev/null

if [ $? != 0 ]; then
	tmux new-session -d -s $SESSION #'nvim .'
	tmux send-keys -t $SESSION 'source venv/bin/activate' C-m
	tmux send-keys -t $SESSION 'nvim .' C-m
	# source venv/bin/activate
	tmux split-window -v 
	tmux send-keys -t $SESSION 'source venv/bin/activate' C-m
	tmux attach-session -t $SESSION
fi

